#!/usr/bin/env bash
#0. World wide web

get_ip_record () {
    result=$(dig "$2.$1" | grep -A1 'ANSWER SECTION:')
    destination=$(echo "$result" | awk '/ANSWER SECTION:/ {getline; print $NF}')
    record=$(echo "$result" | awk '/ANSWER SECTION:/ {getline; print $(NF-1)}')
    echo "The subdomain $2 is a $record record and points to $destination"
}

if [ "$2" ]
then
    get_ip_record "$1" "$2"
elif [ "$1" ]
then
    get_ip_record "$1" "www"
    get_ip_record "$1" "lb-01"
    get_ip_record "$1" "web-01"
    get_ip_record "$1" "web-02"
fi
