#!/usr/bin/env bash
# Install nginx web server

sudo apt-get -y update
sudo apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.html
sudo service nginx restart

# 2. Configure redirection for /redirect_me
sudo sed -i -e "/server_name localhost;/a \
    location /redirect_me { \
        return 301 https://github.com/MaryEhb; \
    }" /etc/nginx/sites-available/default

# 3. Test nginx configuration and restart
sudo nginx -t
sudo service nginx restart
