#!/usr/bin/env bash
# Install nginx web server

sudo apt-get -y update
sudo apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.html
sudo service nginx restart

echo "server {
        listen 80 default_server;
        listen [::]:80 default_server;
        root /var/www/html;
        index index.html index.htm index.nginx-debian.html;
        server_name _;
        location /redirect_me {
		return 301 https://github.com/MaryEhb;
        }
        error_page 404 /404.html;
        location = /404.html {
                internal;
        }
}" > /etc/nginx/sites-available/default

echo "Ceci n'est pas une page" > /var/www/html/404.html

sudo sed -i "/^http {/a \        add_header X-Served-By \"$HOSTNAME\";" /etc/nginx/nginx.conf

sudo nginx -s reload
