#!/usr/bin/env bash
# Install nginx web server

sudo apt-get -y update
sudo apt-get -y install --no-install-recommends software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-2.9 -y
sudo apt-get -y install haproxy=2.9.\*

echo "
frontend web_front
    bind *:80
    mode http
    default_backend web_servers

backend web_servers
    mode http
    balance roundrobin
    server 339431-web-01 34.224.62.130:80 check
    server 339431-web-02 3.94.213.33:80 check
" | sudo tee -a /etc/haproxy/haproxy.cfg

sudo service haproxy start
