#!/usr/bin/env bash
# more than one trap

echo $$ >> /var/run/myscript.pid

trap "echo I hate the kill command;rm /var/run/myscript.pid; exit" SIGTERM
trap "echo Y U no love me?!;rm /var/run/myscript.pid;exit" SIGINT

while true
do
	echo "To infinity and beyond"
done
