#!/usr/bin/env bash
# more than one trap

trap "echo I hate the kill command;rm /var/run/myscript.pid; exit" SIGTERM
trap "echo Y U no love me?!" SIGINT
trap "rm /var/run/myscript.pid;exit"

echo $$ >> /var/run/holbertonscript.pid

while true
do
	echo "To infinity and beyond"
done
