#!/usr/bin/env bash
# displays: The content of the current directory In a list format
#Where only the part of the name after the first dash is displayed

files=$(ls -1)

for file in $files
do
	echo "$(cut -d "-" -f 2 <<< "$file")"
done
