#!/bin/env bash
# 1. Run Nginx as Nginx

pkill apache2

# Change nginx user in nginx.conf
sed -i 's/#user www-data/user nginx/' /etc/nginx/nginx.conf

# Change nginx listen port to 8080 in default site configuration
sed -i 's/80/8080/g' /etc/nginx/sites-available/default

# Start nginx service
sudo -u nginx service nginx restart
