#!/bin/env bash
# 1. Run Nginx as Nginx

# Install nginx if not already installed
sudo apt-get update
sudo apt-get install -y nginx

# Stop nginx service
sudo -u nginx service nginx stop

# Change nginx user in nginx.conf
sed -i 's/#user www-data/user nginx/' /etc/nginx/nginx.conf

# Change nginx listen port to 8080 in default site configuration
sed -i 's/listen 80;/listen 8080;/g' /etc/nginx/sites-available/default

# Start nginx service
sudo -u nginx service nginx start
